### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by technomorph** [nielsdejong/neo4j-playlist-builder#1]
Getting the following error:

(venv) KTEL-MBP-1312:neo4j-playlist-builder djk-tel$ python3 neo4j_spotify_playlist_builder.py
START load graph using spotify api...
b4 create neo4j session...
dropping and creating constraints...
get_tracks...
get_track_audio_featurescks...
Traceback (most recent call last):
  File "/Volumes/Panko/zz Programming Transfers/Machine Learning/Neo 4J/neo4j-playlist-builder/neo4j_spotify_playlist_builder.py", line 340, in <module>
    load_graph_using_spotify_api()
  File "/Volumes/Panko/zz Programming Transfers/Machine Learning/Neo 4J/neo4j-playlist-builder/neo4j_spotify_playlist_builder.py", line 42, in load_graph_using_spotify_api
    neo4j.run("UNWIND $tracks as track CREATE (t:Track{id: track.id}) SET t = track", parameters={'tracks': list(tracks.values())})
  File "/Volumes/Panko/zz Programming Transfers/Machine Learning/Neo 4J/neo4j-playlist-builder/venv/lib/python3.9/site-packages/neo4j/work/simple.py", line 217, in run
    self._autoResult._run(query, parameters, self._config.database, self._config.default_access_mode, self._bookmarks, **kwparameters)
  File "/Volumes/Panko/zz Programming Transfers/Machine Learning/Neo 4J/neo4j-playlist-builder/venv/lib/python3.9/site-packages/neo4j/work/result.py", line 101, in _run
    self._attach()
  File "/Volumes/Panko/zz Programming Transfers/Machine Learning/Neo 4J/neo4j-playlist-builder/venv/lib/python3.9/site-packages/neo4j/work/result.py", line 202, in _attach
    self._connection.fetch_message()
  File "/Volumes/Panko/zz Programming Transfers/Machine Learning/Neo 4J/neo4j-playlist-builder/venv/lib/python3.9/site-packages/neo4j/io/_bolt4x0.py", line 330, in fetch_message
    response.on_failure(summary_metadata or {})
  File "/Volumes/Panko/zz Programming Transfers/Machine Learning/Neo 4J/neo4j-playlist-builder/venv/lib/python3.9/site-packages/neo4j/io/_bolt4x0.py", line 529, in on_failure
    raise Neo4jError.hydrate(**metadata)
neo4j.exceptions.CypherTypeError: Property values can only be of primitive types or arrays thereof. Encountered: Map{spotify -> String("https://open.spotify.com/track/1MUgIUkMkEzybR9HZnyVmj")}.

any ideas?

**Comment by technomorph** [comment]
I was able to solve the above by fixing bad indentations in the code.  But other issues came up.  Seee next issue
