### ISSUE TITLE
Missing GDS????

### ISSUE THREAD

**Issue by technomorph** [nielsdejong/neo4j-playlist-builder#2]
Was able to final get a bit further.
Realized I had to set up AuroaDB and enter my info there.
Getting further but now it fails trying to excute first call in function:
Am I missing the GDS library?

```
def cluster_genres_with_gds(neo4j):
    result = neo4j.run("""
    CALL gds.graph.exists($name) YIELD exists WHERE exists CALL gds.graph.drop($name) YIELD graphName
    RETURN graphName + " was dropped." as message
    """, name='genre-has-artist')
```

Full Output from Start

```
KTEL-MBP-1312:neo4j-playlist-builder djk-tel$ python3 neo4j_spotify_playlist_builder.py
dropping and creating constraints...
creating tracks...
creating albums...
creating artists..
creating genres..
Linking tracks to albums, genres, and artists...
Clustering genres using the GDS library and creating super-genres...
Traceback (most recent call last):
  File "/Volumes/Panko/zz Programming Transfers/Machine Learning/Neo 4J/neo4j-playlist-builder/neo4j_spotify_playlist_builder.py", line 338, in <module>
    load_graph_using_spotify_api()
  File "/Volumes/Panko/zz Programming Transfers/Machine Learning/Neo 4J/neo4j-playlist-builder/neo4j_spotify_playlist_builder.py", line 63, in load_graph_using_spotify_api
    cluster_genres_with_gds(neo4j)
  File "/Volumes/Panko/zz Programming Transfers/Machine Learning/Neo 4J/neo4j-playlist-builder/neo4j_spotify_playlist_builder.py", line 114, in cluster_genres_with_gds
    result = neo4j.run("""
  File "/Users/djk-tel/Library/Python/3.9/lib/python/site-packages/neo4j/work/simple.py", line 217, in run
    self._autoResult._run(query, parameters, self._config.database, self._config.default_access_mode, self._bookmarks, **kwparameters)
  File "/Users/djk-tel/Library/Python/3.9/lib/python/site-packages/neo4j/work/result.py", line 101, in _run
    self._attach()
  File "/Users/djk-tel/Library/Python/3.9/lib/python/site-packages/neo4j/work/result.py", line 202, in _attach
    self._connection.fetch_message()
  File "/Users/djk-tel/Library/Python/3.9/lib/python/site-packages/neo4j/io/_bolt4x0.py", line 330, in fetch_message
    response.on_failure(summary_metadata or {})
  File "/Users/djk-tel/Library/Python/3.9/lib/python/site-packages/neo4j/io/_bolt4x0.py", line 529, in on_failure
    raise Neo4jError.hydrate(**metadata)
neo4j.exceptions.ClientError: There is no procedure with the name `gds.graph.exists` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.
```

**Comment by nielsdejong** [comment]
hi @technomorph ,
Yes, you're correct!
You'll have to use a Neo4j installation with the GDS library installed to run the tool.
If you download Neo4j Desktop and set up a database there, you'll be able to install the GDS library with one click:
https://neo4j.com/download/

GDS for Neo4j Aura is still in a preview state, and not available for the public (yet).

Hope this works,
Niels

**Comment by technomorph** [comment]
Thank you.   After I downloaded and installed Neo4J Desktop was able to 
get it to work.  I made sure I added the GDS library to the Project so it was available to the dB.

Could you please add that to the README file.
Also note to folks that if you set a password for your dB (I used the default neo4j)
That that should be the password that you enter into your "credentials" in the file.

I started playlist with some of the options like 
`plot_kmeans_clusters = False                                      	# Whether to plot the kmeans clusters used for playlists.
min_playlist_size = 10                                              # Cut off for playlists to be grouped as 'misc'
playlist_split_limit = 50                                           # min size for playlists to be chopped up in smaller ones.`

and then re-ran and started getting errors about constraint already existing.
I'm learning how to clear out the dB and will start another issue with info.

thanks

**Comment by nielsdejong** [comment]
Hi @technomorph , thanks for the findings!
I've added a note to the README that the GDS plugin needs to be installed as you suggested.

Thanks,
Niels
