### ISSUE TITLE
Client Error there already exists (Constraint)

### ISSUE THREAD

**Issue by technomorph** [nielsdejong/neo4j-playlist-builder#3]
I've tried a few things to reset / clear the dB.   
Currently it's still showing:
Labels - 1
Properties - 43

here's my current output

```
KTEL-MBP-1312:neo4j-playlist-builder djk-tel$ python3 neo4j_spotify_playlist_builder.py
dropping and creating constraints...
Traceback (most recent call last):
  File "/Volumes/Panko/zz Programming Transfers/Machine Learning/Neo 4J/neo4j-playlist-builder/neo4j_spotify_playlist_builder.py", line 338, in <module>
    load_graph_using_spotify_api()
  File "/Volumes/Panko/zz Programming Transfers/Machine Learning/Neo 4J/neo4j-playlist-builder/neo4j_spotify_playlist_builder.py", line 34, in load_graph_using_spotify_api
    recreate_contraints(neo4j)
  File "/Volumes/Panko/zz Programming Transfers/Machine Learning/Neo 4J/neo4j-playlist-builder/neo4j_spotify_playlist_builder.py", line 82, in recreate_contraints
    neo4j.run("CREATE CONSTRAINT ON (g:Genre) ASSERT g.name IS UNIQUE")
  File "/Users/djk-tel/Library/Python/3.9/lib/python/site-packages/neo4j/work/simple.py", line 217, in run
    self._autoResult._run(query, parameters, self._config.database, self._config.default_access_mode, self._bookmarks, **kwparameters)
  File "/Users/djk-tel/Library/Python/3.9/lib/python/site-packages/neo4j/work/result.py", line 101, in _run
    self._attach()
  File "/Users/djk-tel/Library/Python/3.9/lib/python/site-packages/neo4j/work/result.py", line 202, in _attach
    self._connection.fetch_message()
  File "/Users/djk-tel/Library/Python/3.9/lib/python/site-packages/neo4j/io/_bolt4x0.py", line 330, in fetch_message
    response.on_failure(summary_metadata or {})
  File "/Users/djk-tel/Library/Python/3.9/lib/python/site-packages/neo4j/io/_bolt4x0.py", line 529, in on_failure
    raise Neo4jError.hydrate(**metadata)
neo4j.exceptions.ClientError: There already exists an index called 'constraint_1a952f13'.
```

**Comment by technomorph** [comment]
FIXED BY CLEARING DATABASE: 

 TO CLEAR/RESET NEO4J DATABASE:
1 - In Neo4j Desktop - Select "Open With Neo4J-Browser"

2 - Switch to system database:
```
:use system
```

3 - Show all databases created with the instance:
```
SHOW DATABASES
```

4 - Run the command to clear the database.
```
### CREATE OR REPLACE DATABASE <name>
CREATE OR REPLACE DATABASE neo4j
```

5 - Stop the active DBMS.  Wait a bit.  Restart
